[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dicegame = "FgVujCksmyUpP8bDxv3m4KXoHZ5HC2Jdq4n9PGzf2TYn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/andrew/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
