[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "5ZAzo76efXoLsHWEs1E6KkiRF5fTLxm6udyhEPCM682j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/andrew/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
